### ISSUE TITLE
Página en el repositorio

### ISSUE THREAD

**Issue by ogsilvaa** [nodeschool/lima#1]
En el branch gh-pages hay que depositar la página web a mostrar a través de [nodeschool.io/lima](http://nodeschool.io/lima/), debemos definir estilo y contenido de la página, así como la navegabilidad de la misma.

**Comment by ogsilvaa** [comment]
Referencias
- [Pages Github](https://pages.github.com/)
- [Ayuda de Páginas](https://help.github.com/pages)
- [Jekyll](https://jekyllrb.com/)

**Comment by lupomontero** [comment]
Hola @ogsilvaa, pudiste ver el PR #10 con una propuesta de página por el momento?

**Comment by lupomontero** [comment]
Cierro este issue ya que esto se solucionó hace tiempo en #10 :see_no_evil:
