### ISSUE TITLE
NodeSchool @Laboratoria - 3 Nov 2018

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/lima#11]
Hola todxs,

Se acerca la fecha del próximo NodeSchool en Laboratoria Lima :tada:. Será el sábado 3 de noviembre, de 10am a 5pm como la última vez.

Acá pueden ver el evento en meetup.com: https://www.meetup.com/LimaJS/events/255196155/

Me tomo la libertad de abrir este issue para convocar mentorxs y voluntarixs e ir confirmando por acá (y/o el [Slack de LimaJS](https://holalimajs.herokuapp.com/)).

Basado en el issue anterior (#9) y algunas conversaciones por Slack e email, creo que se han ofrecido las siguientes personas como mentorxs:

* [x] @wixo
* [x] @Xpktro
* [x] @lupomontero
* [x] @PuercoPop (confirmado en comentarios más abajo)
* [x] @lavaldi (confirmada a través de @erikfloresq por email)
* [x] @carmanuelz (confirmado a través de @erikfloresq por email)
* [x] @erikfloresq (confirmado por email)
* [x] @ccarruitero (confirmado en comentarios más abajo)
* [x] @JoshDev1205
* [x] @dsuarezlogans
* [ ] @giancorzo
* [ ] @techfano

@merunga, @ogsilvaa, @talueses: se animarían a participar como mentores?

@MaiaRojas, @developerVilchez, @arun1595: se animan otra vez para echar una mano con la organización el día del evento?

Todxs lxs que quieran confirmar participación porfa asegúrense de registrarse en meetup.com. Si están en lista de espera avisen para que los confirmemos manualmente. Facilita las cosas que estemos todxs en la lista para que no hayan problemas en la puerta el día del evento.

:muscle: :rocket: :star:

**Comment by talueses** [comment]
Si me ayudan con el target y los tópicos, creo que sí ayudaría, @lupomontero :)

**Comment by PuercoPop** [comment]
Confirmo mi presencia!

**Comment by ccarruitero** [comment]
yo puedo colaborar como mentor

**Comment by lupomontero** [comment]
@talueses: en los talleres usamos el [contenido oficial de NodeSchool](https://nodeschool.io/#workshopper-list), principalmente los _workshoppers_ de la sección _core_. En el canal de #nodeschool en el Slack de LimaJS iremos compartiendo info para mentorxs y voluntarixs. En la [página web oficial de NodeSchool](https://nodeschool.io/) puedes ver más sobre la inciativa.

@PuercoPop, @ccarruitero: confirmados! :rocket:

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue (el evento ya pasó hace casi 8 meses :see_no_evil:)

**Comment by ogsilvaa** [comment]
ok
*Oscar Silva*

*Analista de Sistemas*51.997796961
info <https://sites.google.com/site/oscarsilvaanchante/>

 *Salve un árbol. No imprima este correo a menos que sea necesario.*
