### ISSUE TITLE
NodeSchool @Laboratoria - 1 Dic 2018

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/lima#12]
Hola todxs,

Se acerca la fecha del próximo NodeSchool en Laboratoria Lima :tada:. Será el sábado 1 de diciembre, de 10am a 5pm como la última vez.

Acá pueden ver el evento en meetup.com: https://www.meetup.com/LimaJS/events/255218780/

Me tomo la libertad de abrir este issue para convocar mentorxs y voluntarixs e ir confirmando por acá (y/o el [Slack de LimaJS](https://holalimajs.herokuapp.com/)).

Todxs lxs que quieran confirmar participación porfa asegúrense de registrarse en meetup.com. Si están en lista de espera avisen para que los confirmemos manualmente. Facilita las cosas que estemos todxs en la lista para que no hayan problemas en la puerta el día del evento.

:muscle: :rocket: :star: 

cc/ @Xpktro @PuercoPop @lavaldi @carmanuelz @erikfloresq @ccarruitero @JoshDev1205 @dsuarezlogans @giancorzo @techfano @merunga @ogsilvaa @talueses @MaiaRojas @developerVilchez @arun1595

**Comment by lordvalor** [comment]
:+1:  Confirmado, ahi estaremos.

**Comment by lizzie136** [comment]
Entiendo que están confirmados 
* @lupomontero (https://github.com/lupomontero)
* @dsuarezlogans (https://github.com/dsuarezlogans)
* @techfano (https://github.com/techfano)
* @talueses (https://github.com/talueses)
* @JoshDev1205 (https://github.com/JoshDev1205)
* @ccarruitero (https://github.com/ccarruitero)

Si se quieren registrar como mentores, solo contesten este issue y apoyen mañana a que más gente aprenda 💛 😄

**Comment by lupomontero** [comment]
Este evento ya pasó... así que cierro issue...
