### ISSUE TITLE
Uso de este repo para chapter de Lima

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/lima#13]
Hola todxs :wave:,

Junto con la comunidad de @lima-js, desde hace ya varios meses venimos organizando talleres NodeSchool en @Laboratoria con un grupo variado de mentorxs.

* 15 Junio 2019: https://www.meetup.com/LimaJS/events/260138408/
* 13 Abril 2019: https://www.meetup.com/LimaJS/events/260138343/
* 23 Febrero 2019: https://www.meetup.com/LimaJS/events/258223495/
* 19 Enero 2019: https://www.meetup.com/LimaJS/events/257737029/
* 1 Diciembre 2018: https://www.meetup.com/LimaJS/events/255218780/
* 3 Noviembre 2018: https://www.meetup.com/LimaJS/events/255196155/
* 6 Octubre 2018: https://www.meetup.com/LimaJS/events/255049411/

Abro este issue porque el [último PR que se envió el año pasado](https://github.com/nodeschool/lima/pull/10) nunca recibió respuesta de nadie con permisos de escritura en este repo... :see_no_evil: ... así que seguimos sin página web y sin poder usar este repo para temas relacionados a los talleres.

Dado que vamos a continuar con los talleres de NodeSchool (aprox 1 al mes), me gustaría reabrir la conversación para ver si algunxs de los co-organizadorxs de estos eventos pudieran tener permiso de escritura, o por lo menos poder contar con alguien que atienda PRs e issues en este repo?

cc/ @ogsilvaa @talueses @Xpktro @techfano @ccarruitero @JoshDev1205 @dsuarezlogans @giancorzo @MaiaRojas

**Comment by ogsilvaa** [comment]
mil disculpas, sucede que el co-founder esta en uno de esos proyectos suicidas y por mi parte es que fui papá y como comprenderán estuve desconectado hasta del planeta,

Cuenten conmigo para los eventos, para la organización como para el desarrollo de materiales hemos tenido eventos internos , estamos gustosos de colaborar.

Saludos

**Comment by lizzie136** [comment]
Hola @ogsilvaa , cómo te sonaría que puedas hacer a @lupomontero colaborador del chapter/repositorio para que podamos actualizar estas cosas y movernos un poco más rápido? De hecho a estado organizando todos los que hemos tenido y sería chevere poder tenerlos oficialmente en página y esas cosas bonitas :)

**Comment by ogsilvaa** [comment]
Me suena bien, sin embargo es un problema pues llevo pidiendo hace 5 meses
la aprobación de otros 4 colaboradores. Sin embargo en lo que resulta la
aprobación me gustaría poder apoyarlos.

**Comment by lizzie136** [comment]
@ogsilvaa, ya no tanto por curiosidad, pero cuando dices 4 colaboradores a quiénes te refieres? Lo digo porque hace varios meses se sigue organizando el evento a pesar que no estas, creo que Lupo lo deja claro en el issue. Si hay más organizadores sería cool coordinar para hacer más cosas cheveres.

**Comment by lupomontero** [comment]
Gracias por tu respuesta @ogsilvaa y felicidades por la paternidad :star: 

Quienes necesitarían aprobar esto? Podemos incluirlos en este _hilo_?

**Comment by ogsilvaa** [comment]
> @ogsilvaa, ya no tanto por curiosidad, pero cuando dices 4 colaboradores a quiénes te refieres? Lo digo porque hace varios meses se sigue organizando el evento a pesar que no estas, creo que Lupo lo deja claro en el issue. Si hay más organizadores sería cool coordinar para hacer más cosas cheveres.

@lizzie136 nosotros tambien hemos realizado eventos, los colaboradores son Dora Arpi, Alan Azabache, Jeyson Marco y Renzo Camarena, pero como les indico, aun no me aprueba su registro en este chapter, desconozco la causa.

> Gracias por tu respuesta @ogsilvaa y felicidades por la paternidad ⭐️
> 
> Quienes necesitarían aprobar esto? Podemos incluirlos en este _hilo_?

por supuesto, pero no te puedo garantizar la asignación de permisos, pq no depende de mi, sino de NodeSchool, ya se realizó el issue y esta en cola, namas que ya van meses como indico. Solicité también que me den permisos para promover pero de eso no tengo ninguna respuesta.

**Comment by wixo** [comment]
Hola @ogsilvaa, gracias por la predisposición, nos gustaría saber qué eventos pudieron realizar en los últimos meses, nos da curiosidad saber en qué eventos de los listados al comienzo del hilo ustedes pudieron participar y no los tuvimos en cuenta. Creo que a partir de ahora los podemos tener en cuenta para que nos acompañen también.

**Comment by ogsilvaa** [comment]
disculpa la demora, estuvimos realizando eventos en la catolica, en el ISTP argentina en su semana tecnica y en empresas como MDP y SAPIA estos ultimos como inducción al uso de Node. lamentablemente por la poca cantidad que somos (eramos) no tenemos registros de ello. Pero podemos repetir la experiencia junto con laboratoria, yo soy ex alumno del ISTP argentina, asi mismo, mi hija estudia en el colegio.

Hace tiempo en colombia hubo un proyecto de capacitacion de escolares en el uso de node y arduino y fue bastante bueno hasta el cambio de gobierno, me toco ver los indicadores en el cierre del proyecto, la diferencia con peru es que el nivel de nuestros estudiantes es menor por lo que resulta mas complicado, pero sólo eso, mas complicado, no imposible.

Así mismo, pertenezco a la Asociacion Scout del Peru (ya no tan activo por mi bebe) pero alguna vez se habló de llevar estos conceptos de tecnología a esta comunidad pero enfocarlo a sus intereses como clima, progresion interna, redes sociales, etc.

Me gustaria mucho poder reunirnos y comentar directamente todas estas ideas que se recopilaron que desembocaron en la fundacion de este chapter.

**Comment by ccarruitero** [comment]
@ogsilvaa @lupomontero creo que podemos cerrar este issue

**Comment by lupomontero** [comment]
Por mi ok :+1: 

Por otro lado, si se animan, el próximo NodeSchool Lima en @Laboratoria será el sábado 26 de octubre :wink: 

https://www.meetup.com/LimaJS/events/265160398/

**Comment by talueses** [comment]
Me permito preguntar: ¿Cerrar bajo qué conclusión? ¿se va aplicar este repositorio para el capítulo de Lima?, ¿lo aprobaron?

**Comment by lupomontero** [comment]
@talueses: sí, el PR con la página web para el chapter de Lima ya se aprobó hace un buen tiempo. Acá puedes verla: https://nodeschool.io/lima/

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue ya que desde hace ya unos meses estamos usando este repo para el chapter que hay activo en este momento en Lima :wink:
