### ISSUE TITLE
Cuenta de Twitter

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/lima#15]
Hola @ogsilvaa,

Aprovecho a preguntar si tú sabes algo de esta cuenta de Twitter: [NodeSchoolLima - @LimaNode](https://twitter.com/LimaNode)

Existe desde sept 2016 pero no tiene ningún tweet... :thinking:

**Comment by ogsilvaa** [comment]
si, la creamos hace tiempo, pero el publico al que tenemos (estudiantes) no
suele usar twitter por lo que se quedó en desuso, sin embargo se registró
para no perder el usuario, de la misma manera se creo una cuenta en e-quipu
para trabajar con la facultad de ingenieria de la católica, pero el  efecto
fue el mismo, si deseas ubico las credenciales y las compartimos.


*Oscar Silva*

*Analista de Sistemas*51.997796961
info <https://sites.google.com/site/oscarsilvaanchante/>

 *Salve un árbol. No imprima este correo a menos que sea necesario.*

**Comment by lupomontero** [comment]
Hola @ogsilvaa. Te mando un correo para ver este tema, ok?

Creo que sería muy útil que podamos usar esa cuenta para promover los eventos y tener cada vez más llegada.

**Comment by ccarruitero** [comment]
@ogsilvaa @lupomontero se pudo solucionar lo de la cuenta de twitter?

**Comment by lupomontero** [comment]
Le envié un correo a principios de julio a @ogsilvaa pero creo que no he recibido respuesta... :see_no_evil: @ogsilvaa, recibiste mi correo?

**Comment by lupomontero** [comment]
Al no haber tenido respuesta sobre la cuenta de Twitter, y siguiendo la sugerencia de @ccarruitero el sábado pasado en la [NodeSchool que tuvimos en Laboratoria](https://www.meetup.com/LimaJS/events/265160398/), me he tomado la libertad de crear una nueva cuenta en Twitter:

https://twitter.com/node_lima

PS: Traté de crear la cuenta con el _nickname_ `@NodeSchoolLima` pero por algún motivo se creó como `@node_lima` :thinking: ...
