### ISSUE TITLE
Co-locar NodeSchool con un evento para contribuir a Mozilla Firefox

### ISSUE THREAD

**Issue by PuercoPop** [nodeschool/lima#16]
# Propuesta

Co-locar con Nodeschool un evento🕂 para contribuir a Mozilla
Firefox. Tentativamente el de Agosto.

# Motivación

Nodeschool es un evento destinado a un primer acercamiento a la programación y
JavaScript. Ya se han realizado varios talleres con éxito. Cual sería el
segundo paso? Propongo que sea contribuir a Mozilla Firefox.

## Pros

- Los devtools están escritos en HTML/CSS/JS. No se necesita saber más que eso
  para poder contribuir. No es necesario saber C++ o Rust.

- Mozilla ha escrito varios documentos para guiar a potenciales contribuidores:
  [Firefox Developer Tools Docs and Guides][DEV-TOOLS-DOCS] y
  [Codetribute][CODETRIBUTE]. Además de activamente marcar issues como
  `good-first-bug` en su bugtracker y asignar
  [mentores][MENTORED-BUGS] a bugs específicos.

- El setup esta automatizado en su mayoria. `./mach build` asiste al usuario a
  instalar todas la dependencias y configurar mercurial.

- Es un proyecto de alta visibilidad la satisfacción de contribuir a un
  proyecto usado por millones de personas es mayor.

- Es algo que puede interesar a desarrolladores de todos los niveles de
  experiencia, propiciando un espacio para el aprendizaje cooperativo.

- Mozilla es una organización comprometida con apoyar la apertura de la web, la
  privacidad y Software Libre.

## Cons

- Usa mercurial en vez de git. Aunque mercurial es conceptualmente más simple
  es menos popular. Además hay términos de git que en mercurial significa otra
  cosa, como branch.
- En vez de GitHub se contribuye al través de Phabricator.
- El JS es un poco idiosincrásico. ej. No usa JSX, pero con viene eslint
  configurado para asistir a los desarrolladores.

# Agenda Tentativa

- (~1 hora) Demo/Walkthrough del setup.
- (5 minutos) Mercurial Survival Guide
- (5 minutes) Commit guidelines, en particular como indicar el reviewer y otra
  metadata.
- Walkthrough de como usar `arc diff`? Aunque una alternativa sería dejar eso
  para cuando ya se tenga un parche listo para mandar.
- Code! Ya sea mob o pairing. (El resto de la jornada).

# Voluntarios

- @PuercoPop
- …listense otros interesados.

# Siguientes pasos

No tengo claro cual es el mecanismo de consenso. Qué significa
'aprobado'? También me gustaría incluir a @mozillaperu (cc: @ccarruitero) en la medida de lo posible e interés de su parte. De ser aceptado podría empezar a redactar instrucciones simplificadas que sirvan de guia para el walkthrough en un gist.

# Notas

🕂 Diria Hackaton en su acepción original, tal como fue acuñada por OpenBSD. Lamentablemente en la actualidad la palabra esta asociada con una práctica tóxica en mi perspectiva.

[CODETRIBUTE]: https://codetribute.mozilla.org/
[DEV-TOOLS-DOCS]: http://firefox-dev.tools/
[MENTORED-BUGS]: https://bugzilla.mozilla.org/buglist.cgi?f1=bug_mentor&o1=isnotempty&resolution=---&query_format=advanced&list_id=10686903
[Phabricator]: https://phabricator.services.mozilla.com

**Comment by lupomontero** [comment]
Hola @PuercoPop, gracias por compartir la propuesta :star: 

Me parece súper buena idea! Quizás un poco fuera del _scope_ normal de los eventos de NodeSchool, pero al mismo tiempo completamente alineado con la idea de aprender haciendo y contribuyendo...

De hecho, viendo esta propuesta, creo que la idea de re-vivir el concepto original de hackathon es súper valiosa y aplicable a varias iniciativas... a corto plazo es algo que también podríamos hacer para contribuir a los _workshoppers_ core de NodeSchool ([javascripting](https://github.com/workshopper/javascripting), [learnyounode](https://github.com/workshopper/learnyounode), [stream-adventure](https://github.com/workshopper/stream-adventure), ...), así como MDN, Node core, ...

Con respecto a _siguientes pasos_ y _consenso_, propongo que arranquemos conversando por acá y de ahí vemos si agendamos una llamada entre lxs interesadxs para ver cuán factible sería hacer esto en agosto. Como referencia el [próximo NodeSchool está programado para el sábado 24 de agosto](https://www.meetup.com/LimaJS/events/262832852/), así que creo que sí habría tiempo de planear un evento _diferente_.

Hablemos!

cc/ @ogsilvaa @AngelFQC

**Comment by ccarruitero** [comment]
Hola @PuercoPop, está genial tu idea.

Me parece bien si lo podemos hacer junto a los nodeschool pero, para no desviarnos mucho del scope del evento, propondria incluir también algunos proyectos más relacionados como los workshoppers o algún otro proyecto que utilice node. La idea seria que se tuviera a la par gente contribuyendo a mozilla y a los workshoppers por ejemplo.

Lo del setup (descargar mozilla-central, dependencias, ...) me parece que se puede ir avanzando antes del evento.

**Comment by AngelFQC** [comment]
Hola @PuercoPop me parece muy buena la idea! @firefox-devtools tiene el repo del depurador js que está con git y es más fácil contribuir ahí, me parece.

**Comment by PuercoPop** [comment]
>  corto plazo es algo que también podríamos hacer para contribuir a los workshoppers core de NodeSchool (javascripting, learnyounode, stream-adventure, ...)

> propondria incluir también algunos proyectos más relacionados como los workshoppers

La ventaja de mozilla es que hay bastante documentacion sobre como contribuir y hay un esfuerzo sustantivo para marcar los bugs como good-first issue e incluso se le asignan mentores a algunos bugs. De ojear los repos linkeados por @lupomontero, no he visto que ese sea el caso.

No estoy opuesto a la idea de incluir otros proyectos, pero que significaria que un proyecto este incluido? En el caso de Firefox seria un walkthrough sobre el proceso de poco mas de una hora.

Mi intereses no es hijackear NodeSchool sino proveer un segundo paso para que las personas que asisten a NodeSchool puedan continuar aprendiendo haciendo, se aprenda en grupo y se crezca como comunidad. Si hay intereses por un evento para contribuir a Firefox pero consideran que NodeSchool no es el mejor venue para ello  se puede buscar organizarlo a traves de otra organizacion.

> @firefox-devtools tiene el repo del depurador js que está con git y es más fácil contribuir ahí, me parece.

Habia visto esos repos. Pero no me queda claro como partiendo del repo de git tengo una instancia de Firefox corriendo con los cambios locales realizado. La documentacion que encontre esta alrededor de usar mercurial. Si bien el proceso con mercurial y phabricator involucra mas pasos y el uso de herramientas menos populares, no es complicado. Este fin de semana me tomo alrededor de 2 horas encontrar un bug accessible, escribir el parche, commitearlo localmente, crearme las cuestas en bugzilla y phabricator y submitear el parche para revision.

**Comment by AngelFQC** [comment]
> > @firefox-devtools tiene el repo del depurador js que está con git y es más fácil contribuir ahí, me parece.
> 
> Habia visto esos repos. Pero no me queda claro como partiendo del repo de git tengo una instancia de Firefox corriendo con los cambios locales realizado. La documentacion que encontre esta alrededor de usar mercurial. Si bien el proceso con mercurial y phabricator involucra mas pasos y el uso de herramientas menos populares, no es complicado. Este fin de semana me tomo alrededor de 2 horas encontrar un bug accessible, escribir el parche, commitearlo localmente, crearme las cuestas en bugzilla y phabricator y submitear el parche para revision.

No es una instancia de Firefox completo. Es sólo el depurador que puede correr como una aplicación en otra pestaña mientras debuggeas otra... Es más fácil así, yo mandé un PR pequeño hace un tiempo y fue fácil porque sólo te centras en react... (css, js) https://firefox-dev.tools/debugger/docs/getting-setup.html

**Comment by ccarruitero** [comment]
> > corto plazo es algo que también podríamos hacer para contribuir a los workshoppers core de NodeSchool (javascripting, learnyounode, stream-adventure, ...)
> 
> > propondria incluir también algunos proyectos más relacionados como los workshoppers
> 
> La ventaja de mozilla es que hay bastante documentacion sobre como contribuir y hay un esfuerzo sustantivo para marcar los bugs como good-first issue e incluso se le asignan mentores a algunos bugs. De ojear los repos linkeados por @lupomontero, no he visto que ese sea el caso.
> 
> No estoy opuesto a la idea de incluir otros proyectos, pero que significaria que un proyecto este incluido? En el caso de Firefox seria un walkthrough sobre el proceso de poco mas de una hora.
> 
Con lo de incluirlos me referia más que nada a mecionarlos como opción a contribuir el día del evento y que pudieramos dar soporte a los participantes en caso decidan contribuir en alguno de estos repos.
 
Si, no hay muchos issues marcados como easy o good-first en los repos de workshopper; por lo que tal vez nos tocaria a nosotros revisarlos y seleccionar los que se recomiendan hacer.

Otra cosa que se podria hacer con los workshoppers también, es actualizarlos. Hay varios workshoppers que tienen las dependencias desactualizadas y en algunos casos aún utilizan [adventure](https://github.com/workshopper/adventure) o [`workshopper`](https://github.com/workshopper/workshopper) en vez de [`workshopper-adventure`](https://github.com/workshopper/workshopper-adventure).

> Mi intereses no es hijackear NodeSchool sino proveer un segundo paso para que las personas que asisten a NodeSchool puedan continuar aprendiendo haciendo, se aprenda en grupo y se crezca como comunidad. Si hay intereses por un evento para contribuir a Firefox pero consideran que NodeSchool no es el mejor venue para ello se puede buscar organizarlo a traves de otra organizacion.
> 
No veo mal de probar primero como nos va en el nodeschool. Y más adelante vemos como se podria organizar en un evento de mozilla.

**Comment by ccarruitero** [comment]
> > > @firefox-devtools tiene el repo del depurador js que está con git y es más fácil contribuir ahí, me parece.
> > 
> > 
> > Habia visto esos repos. Pero no me queda claro como partiendo del repo de git tengo una instancia de Firefox corriendo con los cambios locales realizado. La documentacion que encontre esta alrededor de usar mercurial. Si bien el proceso con mercurial y phabricator involucra mas pasos y el uso de herramientas menos populares, no es complicado. Este fin de semana me tomo alrededor de 2 horas encontrar un bug accessible, escribir el parche, commitearlo localmente, crearme las cuestas en bugzilla y phabricator y submitear el parche para revision.
> 
> No es una instancia de Firefox completo. Es sólo el depurador que puede correr como una aplicación en otra pestaña mientras debuggeas otra... Es más fácil así, yo mandé un PR pequeño hace un tiempo y fue fácil porque sólo te centras en react... (css, js) https://firefox-dev.tools/debugger/docs/getting-setup.html

Creo que se podria utilizar ambos. Igual no cae mal aprender algo de mercurial.

**Comment by lupomontero** [comment]
Esto ya está en marcha y se llevará a cabo el próximo 14 de diciembre :tada: 

Gracias a todxs por las ideas :star: 

https://www.meetup.com/MozillaPeru/events/jdsqkryzqbjc/

Me tomo la libertad de cerrar este issue en favor de las conversaciones en el [Discord de Mozilla Perú](https://discord.gg/rU2QZAx) y lo que vayamos agregando en el repo de [`mozillaperu/meetups`](https://github.com/mozillaperu/meetups/).
