### ISSUE TITLE
Logo del Capítulo

### ISSUE THREAD

**Issue by ogsilvaa** [nodeschool/lima#2]
Actualmente se está utilizando el sticker oficial de NodeSchool, pero sería mejor diseñar uno que nos identifique antes de empezar a generar los stickers físicos.

**Comment by lizzie136** [comment]
Hola @ogsilvaa, @lupomontero, @wixo, @xpktro, Hice algunas propuestas de logo. Si me dan feedback sería super cool. Si no es necesario, también todo bien :) 
 ![lines-version](https://user-images.githubusercontent.com/3421560/46210782-51ce8600-c2f7-11e8-920c-c32e5c46dbc7.png)
![lines details-version](https://user-images.githubusercontent.com/3421560/46210783-52671c80-c2f7-11e8-9f7c-7c3299049288.png)
![monocolor](https://user-images.githubusercontent.com/3421560/46210784-52671c80-c2f7-11e8-845f-c1c1631468f2.png)

**Comment by ogsilvaa** [comment]
Me gusta mucho el segundo.

El cerro que se Visualiza que representa. Por lo edificios puede ser el
morro solar??

**Comment by lizzie136** [comment]
Si! exacto, es el Morro Solar, iba a ser San Cristobal, pero estoy tratando de no tener símbolos religiosos muy fuertes como la cruz que es bastante representativa. Los edificios son varios que son raros, como el westing, el de interbank, y otros así.

**Comment by ogsilvaa** [comment]
Lo único que se me ocurre para una identificación sin uso de símbolos religiosos es ponerle las antenas, muchas gracias @lizzie136. ¿¿Lo actualizas??

hace poco hice una modificación para que desde el json se listaran los badges y se visualicen automáticamente en la página.
_______
lima.json
=====
{
  "name": "NodeSchool Lima",
  "location": "Lima",
  "country": "PE",
  "region": "Latin America",
  "organizers": [
    "ogsilvaa",
    "gmvxtm"
  ],
  "website": "http://nodeschool.io/lima",
  "repo": "http://github.com/nodeschool/lima",
  ***"image": "nodeschool-lima.svg"***
}

**Comment by lizzie136** [comment]
Like this? 
![lines-version antenas](https://user-images.githubusercontent.com/3421560/46264107-340f4580-c4de-11e8-8613-fee0e90ee2ef.png)

**Comment by lupomontero** [comment]
@lizzie136: me gusta!

@ogsilvaa: dónde está el archivo `lima.json` que mencionas?

**Comment by lizzie136** [comment]
@ogsilvaa entonces lo mando como PR al mismo repo de nodeschool/lima? en una carpeta logo?

**Comment by ogsilvaa** [comment]
> @ogsilvaa entonces lo mando como PR al mismo repo de nodeschool/lima? en una carpeta logo?

Sí a la carpeta 
https://github.com/nodeschool/nodeschool.github.io/tree/source/images

y el json en caso cambie en:

https://github.com/nodeschool/nodeschool.github.io/tree/source/chapters

Para que se visualice en la web de NodeSchool

**Comment by lizzie136** [comment]
Holi de nuevo, 
agregué un PR con el cambio. Gracias! 
https://github.com/nodeschool/nodeschool.github.io/pull/631

**Comment by ogsilvaa** [comment]
Listo!!

![image](https://user-images.githubusercontent.com/1316919/46365073-39cf6d00-c63d-11e8-9c96-ac164c63609b.png)
