### ISSUE TITLE
NodeSchool @Laboratoria: Oct, Nov y Dic

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/lima#9]
Continuando la conversación que quedó un poco abandonada en #8, ahora me lanzo a proponer algo concreto.

Les propongo organizar 3 node schools alojados en Laboratoria el primer sábado de cada mes durante los próximos 3 meses:

• Sábado 6 de octubre
• Sábado 3 de noviembre
• Sábado 1 de diciembre

Cada evento sería día completo (10am-5pm), así que estoy viendo para conseguir algún tipo de catering, pizzas, sanguches, o algo para que la gente pueda almorzar y pasar el día ahí.

Mi propuesta es hacerlo bajo el paraguas de LimaJS, con el apoyo logístico de voluntarixs y venue de Laboratoria.

Quiénes se animan como mentorxs y/o voluntarixs con la organización?

cc/ @ogsilvaa @lizzie136 @wixo @Xpktro @JoshDev1205 @PuercoPop @stephfz @merunga @techfano @ivandevp @giancorzo @MaiaRojas @RuthMeryCardenas @developerVilchez @RuthSalvador @Danielalab @gaposx @chamodev

**Comment by PuercoPop** [comment]
@lupomontero Puedo ofrecerme como mentor para el  sábado 3 de Noviembre

**Comment by lizzie136** [comment]
@lupomontero estaré fuera de Lima para todas esas fechas, pero puedo apoyar buscando los catering y las convocatorias en social media (I'm not an expert tho). Creo que en cuanto a logística la pregunta es si a gente trae sus propias laptops o les prestan de Laboratoria.

**Comment by ogsilvaa** [comment]
Perfecto, cuenta conmigo

**Comment by ogsilvaa** [comment]
> Perfecto, cuenta conmigo
En la fecha de octubre podré llegar en la tarde

**Comment by MaiaRojas** [comment]
Hola, apoyaré como voluntaria octubre y noviembre :)

**Comment by ivandevp** [comment]
Podría apoyar remotamente, la fecha de diciembre creo que si podría estar presencialmente 😃

**Comment by JoshDev1205** [comment]
Confirmo 😀😀

Sorry por la demora en la respuesta

**Comment by dsuarezdev** [comment]
Hola, que tal? soy Danny Suarez de TektonLabs, @giancorzo me paso la voz sobre este evento, y quiero colaborar como mentor, que debo hacer?

**Comment by dsuarezlogans** [comment]
Hola, que tal? soy Danny Suarez de TektonLabs, @giancorzo me paso la voz sobre este evento, y quiero colaborar como mentor, que debo hacer?

**Comment by ccarruitero** [comment]
Hola, yo podria apoyar como mentor o en alguna otra cosa que haga falta.

**Comment by giancorzo** [comment]
Confirmo

**Comment by Xpktro** [comment]
Confirmado como mentor :)

**Comment by lupomontero** [comment]
Gracias a todxs por sumarse al esfuerzo :rocket: :star:

Según mis notas, para este sábado tenemos como mentorxs a:

* @lupomontero
* @wixo
* @xpktro
* @techfano
* @JoshDev1205
* @giancorzo
* @erikfloresq
* @ogsilvaa
* @dsuarezlogans
* @ccarruitero 

También contaremos con lxs siguientes voluntarixs apoyando con la organización:

* @Manuela
* @Lulu (a partir de medio día)
* @MaiaRojas 
* @arun1595

Me podrían re-confirmar asistencia y en qué horario vendrían? El evento es de 10am a 5pm, con un parón para almorzar. Si pueden venir todo el día genial, si no, pueden venir medio día, o la mañana o la tarde...

El taller primer taller, este sábado, está _sold out_ y hay un waiting list de 28 personas (y subiendo)!! Inicialmente arrancamos con un cupo de 40 personas... hoy subimos a 50.

https://www.meetup.com/LimaJS/events/255049411/

También hemos agendado un _hangout_ para hoy a las 7pm para aclarar dudas y conversar con el quipo de mentorxs y voluntarixs. A esa hora estaremos compartiendo link al hangout por acá y por el slack de LimaJS.

Avísenme si nos estamos olvidando de alguien... :see_no_evil: 

:muscle:

**Comment by lupomontero** [comment]
Link al hangout para quien quiera conectarse... https://hangouts.google.com/hangouts/_/vl3wo52p7ve6bjak63fhhujetae

**Comment by lupomontero** [comment]
Propuesta de agenda para este sábado:

| Hora | Actividad
| ------ | --------- |
| 10:00h | Recepción, café, té, ... |
| 10:30h | Hacking... |
| 13:00h | Almuerzo
| 14:00h | Hacking...
| 16:30h | Wrap up, cierre

**Comment by lavaldi** [comment]
Hola @lupomontero este sábado @carmanuelz y yo no podremos asistir, ya que viajamos para las elecciones. Apoyaríamos para los próximos 😉

**Comment by lupomontero** [comment]
@lavaldi: no probs... contamos con ustedes para los próximos talleres :+1:

**Comment by lupomontero** [comment]
Acabo de enviar PR con varias propuestas que venimos conversando estos días: https://github.com/nodeschool/lima/pull/10

**Comment by lupomontero** [comment]
Cierro este issue en favor de #11, donde podemos conversar del próximo evento en particular.
